### ISSUE TITLE
Dashes in Identifiers

### ISSUE THREAD

**Issue by haraldkrischner** [shepherdwind/velocity.js#119]
In Apache's Velocity engine [configuration](https://velocity.apache.org/engine/devel/configuration.html#parser-configuration)  you can find the default behaviour of not allowing dashes in identifier names:
*parser.allows.dash.in.identifiers = false*

Though velocityjs fails on a identifier like $i-blabla, while $i is set.

I forked and applied the changes but this is a breaking change and not configurable…

**Comment by shepherdwind** [comment]
This change will be very difficult, because this need modify some logic when lexical analysis. But for this lib, token and ast is generate by jison, I describe the rule,  and jison generate the code to parse ast.

This part logic is very hard to add some custom feature. The only solution is to realize anthor lexical , which will be very difficult, and for me, I don't use this lib any more. So I don't want to rewrite the parser.
